-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Oct 29, 2023 at 11:45 AM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 7.3.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ciblog1.0`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE `categories` (
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `user_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`created_at`, `id`, `name`, `user_id`) VALUES
('2023-10-29 07:07:40', 1, 'Technology', 0),
('2023-10-29 07:07:57', 2, 'Cafe', 0),
('2023-10-29 07:47:47', 3, 'Travel', 0);

-- --------------------------------------------------------

--
-- Table structure for table `comments`
--

CREATE TABLE `comments` (
  `body` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `email` varchar(255) NOT NULL,
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `post_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `posts`
--

CREATE TABLE `posts` (
  `body` text NOT NULL,
  `category_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `id` int(11) NOT NULL,
  `post_image` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `user_id` int(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `posts`
--

INSERT INTO `posts` (`body`, `category_id`, `created_at`, `id`, `post_image`, `slug`, `title`, `user_id`) VALUES
('<p>What is full stack development? Full stack development is the knowledge of front and back end languages alongwith database systems. It can also include frameworks. The front end includes the visual and the interactive part (often known as the client side). The back end includes the server-side part and the database system manages all the data generated by the user. The frameworks are some pieces of built code that can be utilized by a developer to make a site run more efficiently. It can be made out of either front-end languages or back-end languages, or both.</p><p>The front-end languages mainly include three languages. These are</p><ul><li>HTML</li><li>CSS</li><li>JavaScript</li></ul><p>The back-end languages can include many languages like -</p><ul><li>Python</li><li>Java</li><li>PHP</li><li>C++</li></ul><p>The Database system used can also be chosen from a wide array of choices like SQL lite, MongoDB, MySQL, Oracle, etc.</p><p>The first step in full-stack development can be considered <i>HTML</i>. The full form of HTML is Hyper Text Markup Language. It is used to structure a website and define where and how to place all the contents in it, like the text, images, tables, etc.<br>Then comes <i>CSS</i>, whose full form is Cascading Style Sheet. It is used to style a website and place all the designs and stylisation in a single file. It can also be used in an HTML file itself.<br>Lastly comes <i>JavaScript</i>. JavaScript is a scripting or programming language that is used to make a web page interactive. It is only when JavaScript is used that a website goes from static to dynamic. Some examples of what JavaScript does is that it can change the colour of a button when the cursor comes over it, scrolling a website, zooming in and many other things. Other than this JavaScript can also be used on the server-side, in mobile applications, and also in some video games.</p><p>In the back-end site of a website, many languages can be chosen.</p><ul><li><i>Python</i> is a programming language that is easy to learn and used mainly to integrate systems quickly on a site. It is used for many things due to its vast libraries.</li><li><i>Java</i> is one of the most popular and widely used programming languages that is highly scalable. It can used to make web applications and make a website run efficiently.</li><li><i>C++</i> is a general-purpose language that is highly used for competitive programming and can also be used as a back-end language.</li><li><i>PHP</i> is an open-source, server-side scripting language that is specifically designed for web development. It is known as a server-side scripting language as its code is executed on the server side. The full form of PHP is Hypertext preprocessor.</li></ul><p>Lastly, we come to databases. They are a collection of interrelated data which is used to efficiently insert, retrieve and delete some data. This data can be represented in the form of tables, graphs, reports, etc. Some common databases are Oracle, MongoDB, and SQL.<br><i>Oracle</i> database is a collection of data that is treated as a unit. The purpose of this database is to store and retrieve information related to the query. It is a database server and is used to manage information.<br><i>MongoDB</i> is a popular NoSQL database, and is an open source document-oriented database. The term NoSQL means non-relational. It means that MongoDB isnt based on the table-like relational database structure but provides an altogether different mechanism for the storage and retrieval of data.<br><i>SQL</i>, Structured Query Language, is a standard Database language that is used to create, maintain and retrieve the relational database.</p>', 1, '2023-10-29 07:12:11', 1, 'FSD.jpg', 'Web-Development-Basic-Understanding', 'Web Development (Basic Understanding)', 1),
('<p>In the world of coffee, there\'s a movement that\'s been brewing for quite some time, and it\'s called the \"third wave.\" This movement is all about appreciating coffee as an artisanal craft, and it\'s been changing the way we think about our daily caffeine fix. At the heart of this wave is Third Wave Cafe, a hidden gem that brings this philosophy to life in the most delicious and innovative ways.</p><p><strong>A Taste of Excellence</strong></p><p>When you step into Third Wave Cafe, you are immediately transported to a coffee lover\'s paradise. The aroma of freshly ground beans fills the air, and the warm, welcoming atmosphere invites you to sit down, relax, and savor every moment.</p><p>The star of the show, of course, is the coffee. Third Wave Cafe is dedicated to sourcing the finest beans from around the world and roasting them to perfection. Whether you\'re a fan of a classic espresso, a creamy latte, or a pour-over, you\'ll find that the coffee here is a cut above the rest. The baristas at Third Wave Cafe are true artists, and they take pride in crafting each cup with precision and care.</p><p><strong>Beyond Coffee</strong></p><p>While Third Wave Cafe is undoubtedly a coffee lover\'s paradise, it\'s not just about the beans. The menu is diverse, offering a range of beverages to cater to every palate. If coffee isn\'t your thing, you can explore their refreshing iced teas or a variety of other innovative drinks. Whether you\'re in the mood for a matcha latte, a chai tea, or a delightful cold brew, Third Wave Cafe has you covered.</p><p><strong>A Place to Savor</strong></p><p>It\'s not just the coffee and beverages that make Third Wave Cafe special; it\'s the entire experience. The cafe is designed with a contemporary and cozy aesthetic that provides the perfect backdrop for a casual chat, a study session, or some much-needed alone time. The comfortable seating, soothing music, and friendly staff all contribute to a memorable visit.</p><p><strong>Community and Sustainability</strong></p><p>Third Wave Cafe isn\'t just about great coffee; it\'s also committed to being a positive force in the community and for the environment. The cafe actively engages with local artists and musicians, hosting events and live performances to create a sense of community and promote local talent. Moreover, the cafe takes sustainability seriously by implementing eco-friendly practices, from compostable cups to sourcing coffee beans from ethical and environmentally responsible suppliers.</p><p><strong>A Coffee Revolution</strong></p><p>If you\'re a coffee enthusiast looking for a place that celebrates the art of coffee making while offering a delightful menu of other beverages, Third Wave Cafe is a must-visit. It\'s not just a cafe; it\'s a destination for those who appreciate the finer details of coffee culture and a welcoming spot for everyone to enjoy quality beverages in a relaxed and inviting atmosphere.</p><p>So, the next time you find yourself in need of a caffeine fix, or if you simply want to unwind with a refreshing tea or another innovative beverage, give Third Wave Cafe a try. You\'ll find yourself immersed in the third wave of coffee, where passion and innovation come together in a delightful cup.</p>', 2, '2023-10-29 07:47:29', 2, 'third-wave-cafe.jpg', 'Sip-the-Future-at-Third-Wave-Cafe-Where-Coffee-Meets-Innovation', ' Sip the Future at Third Wave Cafe: Where Coffee Meets Innovation', 1),
('<p>A trip to Shimla, nestled in the serene Himalayan foothills, is a journey through nature\'s enchanting wonderland. The moment one arrives in this picturesque hill station, the crisp mountain air, lush green valleys, and the majestic snow-capped peaks welcome you to a world of tranquillity and beauty. The charming colonial architecture of Shimla adds a touch of nostalgia to the experience, with the Ridge and Mall Road brimming with vibrant markets and cozy cafes. Shimla offers a unique blend of adventure and relaxation. Whether it\'s strolling through pine forests, embarking on treks to higher altitudes, or simply sipping a warm cup of tea while gazing at the scenic landscapes, Shimla\'s beauty leaves an indelible mark on the soul. The journey to Shimla is a testament to the magical allure of the mountains, making it an unforgettable destination for those seeking a respite from the hustle and bustle of daily life.</p>', 3, '2023-10-29 07:52:35', 3, 'IMG_20180721_132920.jpg', 'Trip-to-shimla', 'Trip to shimla', 1),
('<p>Object-oriented programming, or OOP in short, gives you a particular methodology for implementing large and complex programming projects in a very simple manner. The methodology uses the structure of classes and objects, and four OOP principles, namely abstraction, encapsulation, inheritance and polymorphism, to simplify the large programming projects.</p><p>All programming languages are not based on this OOP model of classes and objects, and some are known as procedural programming languages. But most of the modern general-purpose programming languages, such as C++, C#, Java, and Python, are object-oriented programming languages.&nbsp;</p><p><strong>Benefits of Object Oriented Programming:&nbsp;</strong></p><ol><li>The most important benefit of an object-oriented approach is that you tend to build any project in a more organised manner, making the development process very efficient.</li><li>The second benefit is that an object-oriented approach helps you implement real-world scenarios very naturally.&nbsp;</li><li>The third benefit is that the modification and updation of each independent module is easier in this case.&nbsp;</li></ol><p>All of these benefits are the requirements of a good software development methodology</p>', 1, '2023-10-29 08:02:52', 4, 'whatis-object_oriented_programming.png', 'Object-Oriented-Programming', 'Object Oriented Programming', 1);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `email` varchar(255) NOT NULL,
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `register_date` timestamp NOT NULL DEFAULT current_timestamp(),
  `username` varchar(255) NOT NULL,
  `zipcode` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`email`, `id`, `name`, `password`, `register_date`, `username`, `zipcode`) VALUES
('pk@gmail.com', 1, 'Parth', '81dc9bdb52d04dc20036dbd8313ed055', '2023-10-28 13:35:56', 'pk19', '122009');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `comments`
--
ALTER TABLE `comments`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

--
-- AUTO_INCREMENT for table `comments`
--
ALTER TABLE `comments`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `posts`
--
ALTER TABLE `posts`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
